# Generated by Django 6.1.1 on 2026-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Eqqa Enterprise', max_length=200)),
                ('category', models.CharField(default='[CONFIRM BUSINESS CATEGORY]', max_length=200)),
                ('tagline', models.TextField(default='[CONFIRM TAGLINE]')),
                ('description', models.TextField(default='[CONFIRM BUSINESS DESCRIPTION]')),
                ('location', models.CharField(default='[CONFIRM LOCATION]', max_length=300)),
                ('phone', models.CharField(default='[CONFIRM PHONE]', max_length=50)),
                ('whatsapp', models.CharField(default='[CONFIRM WHATSAPP]', max_length=50)),
                ('address', models.TextField(default='[CONFIRM ADDRESS]')),
                ('email', models.EmailField(blank=True, default='[CONFIRM EMAIL]', max_length=254)),
                ('social_facebook', models.URLField(blank=True, default='[CONFIRM FACEBOOK]')),
                ('social_instagram', models.URLField(blank=True, default='[CONFIRM INSTAGRAM]')),
                ('opening_hours', models.TextField(default='[CONFIRM OPENING HOURS]')),
                ('years_in_business', models.CharField(default='[CONFIRM YEARS]', max_length=50)),
                ('review_rating', models.CharField(default='[CONFIRM RATING]', max_length=10)),
                ('primary_cta_label', models.CharField(default='Order on WhatsApp', max_length=100)),
                ('primary_cta_link', models.URLField(default='https://wa.me/[CONFIRM_WHATSAPP_NUMBER]')),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Info',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='[CONFIRM CAPTION]', max_length=200)),
                ('category', models.CharField(choices=[('product', 'Product'), ('store', 'Store / Location'), ('behind_the_scenes', 'Behind the Scenes'), ('event', 'Event / Customer')], default='product', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefit', models.TextField(help_text='Key customer benefit')),
                ('price', models.CharField(blank=True, default='[CONFIRM PRICE]', max_length=100)),
                ('options', models.TextField(blank=True, help_text='Flavours, sizes, variants')),
                ('availability', models.CharField(blank=True, default='[CONFIRM AVAILABILITY]', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
