# Generated by Django 6.1.1 on 2026-09-03 09:01

from django.db import migrations


def load_initial_data(apps, schema_editor):
    BusinessInfo = apps.get_model("eqqa_api", "BusinessInfo")
    Product = apps.get_model("eqqa_api", "Product")
    GalleryItem = apps.get_model("eqqa_api", "GalleryItem")
    FAQ = apps.get_model("eqqa_api", "FAQ")
    WhyChooseReason = apps.get_model("eqqa_api", "WhyChooseReason")

    if not BusinessInfo.objects.exists():
        BusinessInfo.objects.create(
            name="Eqqa Enterprise",
            category="Kuih & Snacks",
            tagline="Home-style kuih and snacks for your everyday cravings.",
            description="Eqqa Enterprise prepares and sells local kuih and snacks. [CONFIRM FULL BUSINESS DESCRIPTION]",
            location="[CONFIRM LOCATION]",
            phone="[CONFIRM PHONE]",
            whatsapp="[CONFIRM WHATSAPP]",
            address="[CONFIRM ADDRESS]",
            email="[CONFIRM EMAIL]",
            social_facebook="[CONFIRM FACEBOOK URL]",
            social_instagram="[CONFIRM INSTAGRAM URL]",
            opening_hours="[CONFIRM OPENING HOURS]",
            years_in_business="[CONFIRM YEARS IN BUSINESS]",
            review_rating="[CONFIRM REVIEW RATING]",
            primary_cta_label="Order on WhatsApp",
            primary_cta_link="https://wa.me/[CONFIRM_WHATSAPP_NUMBER]",
        )

    if not Product.objects.exists():
        Product.objects.bulk_create([
            Product(
                name="[CONFIRM OFFERING 1]",
                description="[CONFIRM DESCRIPTION]",
                benefit="[CONFIRM KEY BENEFIT]",
                price="[CONFIRM PRICE]",
                options="[CONFIRM OPTIONS / FLAVOURS]",
                availability="[CONFIRM AVAILABILITY]",
                is_featured=True,
                order=1,
            ),
            Product(
                name="[CONFIRM OFFERING 2]",
                description="[CONFIRM DESCRIPTION]",
                benefit="[CONFIRM KEY BENEFIT]",
                price="[CONFIRM PRICE]",
                options="[CONFIRM OPTIONS / FLAVOURS]",
                availability="[CONFIRM AVAILABILITY]",
                is_featured=True,
                order=2,
            ),
            Product(
                name="[CONFIRM OFFERING 3]",
                description="[CONFIRM DESCRIPTION]",
                benefit="[CONFIRM KEY BENEFIT]",
                price="[CONFIRM PRICE]",
                options="[CONFIRM OPTIONS / FLAVOURS]",
                availability="[CONFIRM AVAILABILITY]",
                is_featured=True,
                order=3,
            ),
        ])

    if not GalleryItem.objects.exists():
        GalleryItem.objects.bulk_create([
            GalleryItem(caption="[REAL PHOTO NEEDED] Product photo", category="product", order=1),
            GalleryItem(caption="[REAL PHOTO NEEDED] Store / location", category="store", order=2),
            GalleryItem(caption="[REAL PHOTO NEEDED] Behind the scenes", category="behind_the_scenes", order=3),
            GalleryItem(caption="[REAL PHOTO NEEDED] Event / customer", category="event", order=4),
        ])

    if not FAQ.objects.exists():
        FAQ.objects.bulk_create([
            FAQ(question="Where are you located?", answer="[CONFIRM LOCATION]", order=1),
            FAQ(question="What are your opening hours?", answer="[CONFIRM OPENING HOURS]", order=2),
            FAQ(question="What payment methods are accepted?", answer="[CONFIRM PAYMENT METHODS]", order=3),
            FAQ(question="Do you provide delivery?", answer="[CONFIRM DELIVERY AREA / METHOD]", order=4),
            FAQ(question="Can I order for events?", answer="[CONFIRM EVENT ORDER POLICY]", order=5),
            FAQ(question="How much notice is required?", answer="[CONFIRM LEAD TIME]", order=6),
            FAQ(question="Is the product halal?", answer="[CONFIRM HALAL STATUS]", order=7),
            FAQ(question="How do I order?", answer="[CONFIRM ORDERING PROCESS]", order=8),
        ])

    if not WhyChooseReason.objects.exists():
        WhyChooseReason.objects.bulk_create([
            WhyChooseReason(
                title="[CONFIRM REASON 1]",
                explanation="[CONFIRM WHY CUSTOMERS CHOOSE THIS]",
                order=1,
            ),
            WhyChooseReason(
                title="[CONFIRM REASON 2]",
                explanation="[CONFIRM WHY CUSTOMERS CHOOSE THIS]",
                order=2,
            ),
            WhyChooseReason(
                title="[CONFIRM REASON 3]",
                explanation="[CONFIRM WHY CUSTOMERS CHOOSE THIS]",
                order=3,
            ),
        ])


def delete_initial_data(apps, schema_editor):
    BusinessInfo = apps.get_model("eqqa_api", "BusinessInfo")
    Product = apps.get_model("eqqa_api", "Product")
    GalleryItem = apps.get_model("eqqa_api", "GalleryItem")
    FAQ = apps.get_model("eqqa_api", "FAQ")
    WhyChooseReason = apps.get_model("eqqa_api", "WhyChooseReason")
    BusinessInfo.objects.all().delete()
    Product.objects.all().delete()
    GalleryItem.objects.all().delete()
    FAQ.objects.all().delete()
    WhyChooseReason.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eqqa_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, delete_initial_data),
    ]
