# Generated by Django 6.1.1 on 2026-09-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqqa_api', '0002_auto_20260903_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='achievement',
            field=models.CharField(blank=True, default='Champion, Kuih Cap competition (Sarawak district level), Wellbest Carnival 2025', max_length=300),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='claim_1',
            field=models.CharField(blank=True, default='100% fresh ingredients', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='claim_2',
            field=models.CharField(blank=True, default='No preservatives', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='delivery_methods',
            field=models.CharField(blank=True, default='Self-delivery, runner, or delivery by bus', max_length=300),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='facebook_name',
            field=models.CharField(blank=True, default='Erica Sandra', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='ordering_channels',
            field=models.CharField(blank=True, default='WhatsApp, TikTok, and events', max_length=300),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='phone_secondary',
            field=models.CharField(blank=True, default='013-566 9234', max_length=50),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='social_tiktok',
            field=models.URLField(blank=True, default='[TO BE CONFIRMED]'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='target_customers',
            field=models.CharField(blank=True, default='Adults, children, families, and groups of friends', max_length=300),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='tiktok_name',
            field=models.CharField(blank=True, default='Eqqa Enterprise', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.TextField(default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='category',
            field=models.CharField(default='Kuih & Snacks', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='description',
            field=models.TextField(default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='email',
            field=models.EmailField(blank=True, default='[TO BE CONFIRMED]', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='location',
            field=models.CharField(default='Sibu, Sarawak', max_length=300),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='opening_hours',
            field=models.TextField(default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='phone',
            field=models.CharField(default='011-1408 0050', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='primary_cta_link',
            field=models.URLField(default='https://wa.me/[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='review_rating',
            field=models.CharField(default='[TO BE CONFIRMED]', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='social_facebook',
            field=models.URLField(blank=True, default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='social_instagram',
            field=models.URLField(blank=True, default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='tagline',
            field=models.TextField(default='[TO BE CONFIRMED]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='whatsapp',
            field=models.CharField(default='[TO BE CONFIRMED: primary WhatsApp number]', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='years_in_business',
            field=models.CharField(default='[TO BE CONFIRMED]', max_length=50),
        ),
    ]
